# -*- coding: utf-8 -*-
"""perulangan while.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X9biq_tY9MEhJS0XUit7oLutlEkbutZp
"""

while (1 + 2 == 3):
  print('Hallo Dunia!')

i = 1

while i <= 5:
  print(i)
  i += 1

listkota = ['jakarta', 'depok', 'bekasi', 'solo', 'jogjakarta', 'semarang', 'makassar']

# bermain index
i = 0
while i < len(listkota):
  print(liskota[i])
  i += 1

# bermain pop
while listkota:
  print(listkota.pop(0))

a = int(input('salah, masukkan lagi: '))

while a % 2 != 1 or a <= 50:
  a = int(input('salah,masukkan lagi: '))

print('benar')

listkota = ['jakarta', 'surabaya', 'depok', 'bekasi', 'solo', 'jogjakarta', 'semarang', 'makassar']

# skip jika i adalah bilangan genap
# dan i lebih dari 0
i = -1
while i < len(listkota):
  i += 1
  if i % 2 == 0 and i > 0:
    print('skip')
    continue

  # tidak dieksekusi ketika continue dipanggil
  print(listkota[i])

listkota = ['jakarta', 'surabaya', 'depok', 'bekasi', 'solo', 'jogjakarta', 'semarang', 'makassar']

KotaYangDicari = input('masukkan nama kota yang dicari: ')


i = 0
while i < len(listkota):
  if listkota[i].lower() == KotaYangDicari.lower():
    print('ketemu di index', i)
    break

  print('bukan', listkota[i])
  i += 1

listkota = ['jakarta', 'surabaya', 'depok', 'bekasi', 'solo', 'jogjakarta', 'semarang', 'makassar']

KotaYangDicari = input('masukkan nama kota yang dicari: ')

i = 0
while i < len(listkota):
  if listkota[i].lower() == KotaYangDicari.lower():
    print('ketemu di index', i)
    break

  print('bukan', listkota[i])
  i += 1
else:
  print('Maaf, kota yang anda cari tidak ditemukan.')

