# -*- coding: utf-8 -*-
"""python1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QcfzGRN5JqeRDJkqUYCITwOtplQ3OnQ5
"""

list_kosong = []

list_buah = ["pisang", "nanas", "melon", "durian"]

list_angka = [100,200,1000,2000]

list_campur = ["nasi", 100,200,1000, "ikan", True]

print ("list_kosong, list",list_kosong)

print ("isi list buah", list_buah)

print ("isi list angka", list_angka)

print ("isi list campur", list_campur)

print (list_buah [0])

print (list_buah [1])

print (list_buah [2])

print (list_buah [3])

print (list_buah[-1])

print (list_buah [-2])

print (list_angka [-3])

print(list_buah[0:1])

print(list_buah[0:2])

print(list_buah[1:3])

print(list_buah[2:3])

print (list_buah [0:1:2])

print(list_buah [0:-1])

print (list_buah[1:])

print(list_buah)

list_buah[0] = "apel"

list_buah [-3] = "jambu"

print (list_buah)

list_buah [-4 ]= "pepaya"

list_buah.append("duku")

print(list_buah)

list_buah.insert (2, "manggis")

print(list_buah)

list_buah.remove("melon")

print(list_buah)

del list_buah[1]

print(list_buah)

print(list_angka)

a = [1, 2,3]
b = ["a"]
c = [True, "b", False]

listbaru = a+b+c

print (listbaru)

list_buah.sort()
print(list_buah)

list_angka.sort()
print(list_angka)

list_angka [1] = '3'

list_angka [2] = "2"

list_angka [-1] = "4"

print (list_angka)