# -*- coding: utf-8 -*-
"""Tugas 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PuK0Mr2-AP99OLwKyt1rPjTzClgFWOnY
"""

tuple_jenis_kelamin = ("laki-laki", "perempuan")

tuple_kosong = ()

tuple_status_perkawinan = "menikah", "lajang"

tuple_lulus = tuple(["lulus", "tidak lulus"])

print(tuple_jenis_kelamin[1])

print(tuple_jenis_kelamin[0])

tuple_tunggal =(10, )

print(type((10)))

print(type((10,)))

print(tuple_jenis_kelamin[-1])

print(tuple_jenis_kelamin[-2])

tuple_buah = ('Pisang', 'Nanas', 'Melon', 'Durian')

a = (1, 2, 3)
b = (50, 60,70)

c = a + b
c

nilai_semester_1 = (80, 50,70,100, 70)

max (nilai_semester_1)

len (nilai_semester_1)

min (nilai_semester_1)

mahasiswa = ('Haris Azhari Ramadhan', 'Pangkalpinang', '19')

nama, asal, umur = mahasiswa

print('mahasiswa:',mahasiswa)

print('nama:', mahasiswa [0])
print('asal:', mahasiswa [1])
print('usia:', mahasiswa [2])