# -*- coding: utf-8 -*-
"""Tugas tanggal 22/12/2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cnxa2H5LOKr4FKaQsQ25i_0OvpjzUgWL
"""

#membuat fungsi
def salam ():
  print ("Hello, Selamat Pagi haris")

## Pemanggilan fungsi
salam()

#membuat fungsi
def salam ():
  print ("Hello, Selamat Pagi haris")

## Pemanggilan fungsi
salam()
salam()
salam()

#pemanggilan fungsi parameter
def salam(ucapan):
    print(ucapan)
salam("Selamat Siang")

#membuat fungsi dengan parameter
def luas_segitiga(alas, tinggi):
    luas = (alas * tinggi) / 2
    print ("Luas segitiga: %f" % luas)

#pemanggilan fungsi
luas_segitiga(4, 6)

def luas_persegi(sisi):
    luas = sisi * sisi
    return luas

#pemanggilan fungsi
print ("Luas Persegi: %d" % luas_persegi (6))

# membuat variabel global
nama = "Belajar Kode"
versi = "1.0.0"

def help():
    # ini variabel lokal
    nama = "Programku"
    versi = "1.0.1"
    # mengakses variabel lokal
    print ("Nama: %s" % nama)
    print ("Versi: %s" % versi)

    # mengakses variabel global
    print ("Nama: %s" % nama)
    print ("Versi: %s" % versi)

    # memanggil fungsi help()
    help()

nama = "Belajar Kode"
versi = "1.0.0"

def help():
    nama = "Programku"
    versi = "1.0.1"
    print ("nama: %s" % nama)
    print ("versi: %s" % versi)

# mengakses variabel global
print ("nama: %s" % nama)
print ("versi: %s" % versi)

# membuat variabel global
nama = "Nama, Tanggal lahir"
versi = "Haris Azhari Ramadhan, 03 November 2004"

def help():
    # ini variabel lokal
    nama = "Hobi, jurusan, tempat tinggal"
    versi = "Menggambar, Ilmu komputer, Kacang Pedang"
    # mengakses variabel lokal
    print ("Nama: %s" % nama)
    print ("Versi: %s" % versi)

# mengakses variabel global
print ("Nama: %s" % nama)
print ("Versi: %s" % versi)

# memanggil fungsi help()
help()

buku = []
# fungsi untuk menampilkan semua data
def show_data():
    if len(buku) <= 0:
        print("BELUM ADA DATA")
    else:
      for indeks in range(len(buku)):
          print("[{}]] {}".format(indeks, buku[indeks]))

 # fungsi untuk menambah data
def insert_data():
    buku_baru = input("Judul Buku: ")
    buku.append(buku_baru)

# fungsi untuk edit data
def edit_data():
    show_data()
    indeks = int(input("Inputkan ID buku: "))
    if indeks > len(buku):
       print("ID salah")
    else:
        judul_baru = input("Judul baru: ")
        buku[indeks] = judul_baru

 # fungsi untuk edit data
def delete_data():
    show_data()
    Indeks = int(input("Inputkan ID buku: "))
    if indeks > len(buku):
       print("ID salah")
    else:
        buku.remove(buku[Indeks])

 # fungsi untuk menampilkan menu
def show_menu():
    print("\n")
    print("---------- MENU ----------")
    print("[1] Show Data")
    print("[2] Insert Data")
    print("[3] Edit Sata")
    print("[4] Delele Data")
    print("[5] Exit")

    menu = input("PILIH MENU> ")
    print("\n")

    if int(menu) == 1:
      show_data()
    elif int(menu) == 2:
      insert_data()
    elif int(menu) == 3:
      edit_data()
    elif int(menu) == 4:
      delete_data()
    elif int(menu) == 5:
     exit()
    else:
      print("Salah pilih!")

if __name__ == "__main__":

    while True:
        show_menu()

