# -*- coding: utf-8 -*-
"""tugas 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aJvLViFq113EshikSQ8QxOQZOAQPvk7q
"""

buah_yang_tersedia = ['jeruk', 'mangga', 'melon']
buah_yang_dicari = input('masukkan nama buah dalam huruf kecil:')

if True:
  print('kode program ini akan dieksekusi')


if False:
  print('kode program ini tidak akan dieksekusi')


print('kode program ini akan selalu dieksekusi karena tidak termasuk pada program')

if 10 > 5: #
 print('Nilai 10 lebih dari 5')

nilai = int(input('masukkan nilai: '))
usia = int(input('masukkan usia: '))

if nilai >= 75:
  if (usia < 15):
    print('selamat adek, kamu lulus! ')
  else:
    print('selamat kakak, kamu lulus! ')
else:
  if (usia < 15):
    print('mohon maaf dek, coba lagi ya! ')
  else:
    print('mohon maaf kak, coba lagi ya! ')

nilai = int(input('85: '))

...

print('Dolphin', end=' ')
print('ML', end=' ')

a = 5
b = 6
print('a','+', 'b', '=', 'c')

nilai = int(input('Masukkan Nilai Anda'))
print('Nilai anda adalah:', nilai, '/A')
if nilai >= 90:
  print('Selamat, anda lulus!')
else :
  print('Maaf, anda tidak lulus.')

nilai =int(input('Masukkkan Nilai: '))

if nilai >= 90:
  print('Predikat A')
elif nilai >= 80:
  print('Predikat B')
elif nilai >= 60:
  print('Predikat C')
elif nilai >= 40:
  print('Predikat D')
else :
  print('Predikat E')

buah_yang_tersedia = ['jeruk', 'mangga', 'melon']
buah_yang_dicari = input('Masukkan nama buah dalam huruf kecil: ')

if (buah_yang_dicari in buah_yang_tersedia):
  print('Buah yang anda cari tersedia!')
else :
  print('Buah yang anda cari tidak tersedia!')